backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: "static/img"
public_folder: "/img"
collections:
  ##
  # Specialty data config
  ##
  # role metadata for role slider
  - label: "Role metadata"
    name: "role-data"
    folder: "data/roles/"
    format: "json"
    identifier_field: "name"
    create: true
    fields:
      - {label: "Short Name", name: "title", widget: "string"}
      - {label: "Role Name", name: "name", widget: "string"}
      - {label: "Display Order", name: "order", widget: "number"}
      - {label: "Color", name: "color", widget: "color"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Link", name: "role_link", widget: "string"}
      - {label: "Description", name: "role_text_md", widget: "markdown"}
      - label: "Job Information"
        name: "jobs"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Link", name: "job_link", widget: "string"}
          - {label: "Icon", name: "icon", widget: "string"}
  # role landing page
  - label: "Role landing pages"
    name: "role-landing"
    files:
      - label: "Healers"
        name: "healers"
        file: "content/jobs/healers/_index.md"
        fields:
        - {label: "Body", name: "body", widget: "markdown"}
        - label: "Menu hierarchy"
          name: "menu"
          widget: "hidden"
          default:
            main:
              name: "Healers"
              parent: "jobs"
        - label: "Role"
          name: "role"
          widget: "hidden"
          default: "healer"
  # user "profiles"
  - label: "Author profile"
    name: "author-profile"
    folder: "data/author/"
    format: "json"
    identifier_field: "username"
    media_folder: '/static/img/profile'
    public_folder: '/img/profile'
    create: true
    fields:
      - {label: "Username", name: "username", widget: "string"}
      - {label: "Profile Image", name: "image", widget: "image", choose_url: false}
      - {label: "Display Name", name: "name", widget: "string"}
      - label: "Social information"
        name: "socials"
        widget: "object"
        fields:
          - {label: "Discord Name", name: "discord_id", widget: "string"}
  # encounter metadata
  - label: "Encounter metadata"
    name: "encounter-guide"
    folder: "data/encounter"
    format: "json"
    identifier_field: "category"
    create: true
    fields:
      - {label: "Category", name: "category", widget: "string"}
      - label: "Encounters" 
        name: "encounters"
        widget: "list"
        fields:
          - {label: "Identifier", name: "id", widget: "string"}
          - {label: "Name of Encounter", name: "name", widget: "string"}
          - {label: "Image Link", name: "image_link", widget: "string"}
          - {label: "Encounter Link", name: "encounter_link", widget: "string"}
  ##
  # Scholar guide
  ##
  - label: "Scholar guide"
    name: "sch-guide"
    media_folder: "/static/img/jobs"
    public_folder: "/img/jobs"
    files:
      - label: "Landing page"
        name: "landing"
        file: "content/jobs/healers/scholar/_index.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Leveling Guide"
        name: "leveling-guide"
        file: "content/jobs/healers/scholar/leveling-guide.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Author(s)"
            name: "authors"
            widget: "relation"
            multiple: true
            collection: "author-profile"
            search_fields: ["username", "name"]
            value_field: "username"
            display_fields: ["username", "name"]
          - {label: "Patch", name: "patch", widget: "string"}
          - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
          - label: "Changelog entry"
            name: "changelog"
            widget: "list"
            summary: "{{fields.date}}: {{fields.message}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Message", name: "message", widget: "string"}
      - label: "Basic guide"
        name: "basic-guide"
        file: "content/jobs/healers/scholar/basic-guide.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Author(s)"
            name: "authors"
            widget: "relation"
            multiple: true
            collection: "author-profile"
            search_fields: ["username", "name"]
            value_field: "username"
            display_fields: ["username", "name"]
          - {label: "Patch", name: "patch", widget: "string"}
          - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
          - label: "Changelog entry"
            name: "changelog"
            widget: "list"
            summary: "{{fields.date}}: {{fields.message}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Message", name: "message", widget: "string"}
      - label: "Skills overview"
        name: "skills-overview"
        file: "content/jobs/healers/scholar/skills-overview.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Author(s)"
            name: "authors"
            widget: "relation"
            multiple: true
            collection: "author-profile"
            search_fields: ["username", "name"]
            value_field: "username"
            display_fields: ["username", "name"]
          - {label: "Patch", name: "patch", widget: "string"}
          - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
          - label: "Changelog entry"
            name: "changelog"
            widget: "list"
            summary: "{{fields.date}}: {{fields.message}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Message", name: "message", widget: "string"}
      - label: "Openers"
        name: "openers"
        file: "content/jobs/healers/scholar/openers.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Author(s)"
            name: "authors"
            widget: "relation"
            multiple: true
            collection: "author-profile"
            search_fields: ["username", "name"]
            value_field: "username"
            display_fields: ["username", "name"]
          - {label: "Patch", name: "patch", widget: "string"}
          - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
          - label: "Changelog entry"
            name: "changelog"
            widget: "list"
            summary: "{{fields.date}}: {{fields.message}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Message", name: "message", widget: "string"}
      - label: "Frequently Asked Questions"
        name: "faq"
        file: "content/jobs/healers/scholar/faq.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "qna"}
          - {label: "Patch", name: "patch", widget: "string"}
          - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Author(s)"
            name: "authors"
            widget: "relation"
            multiple: true
            collection: "author-profile"
            search_fields: ["username", "name"]
            value_field: "username"
            display_fields: ["username", "name"]
          - label: "Changelog entry"
            name: "changelog"
            widget: "list"
            summary: "{{fields.date}}: {{fields.message}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Message", name: "message", widget: "string"}
          - label: "FAQ Entry"
            name: "qna"
            widget: "list"
            summary: "{{fields.question}}: {{fields.answer}}"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "markdown"}
      - label: "Advanced guide"
        name: "advanced-guide"
        file: "content/jobs/healers/scholar/advanced-guide.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Author(s)"
            name: "authors"
            widget: "relation"
            multiple: true
            collection: "author-profile"
            search_fields: ["username", "name"]
            value_field: "username"
            display_fields: ["username", "name"]
          - {label: "Patch", name: "patch", widget: "string"}
          - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
          - label: "Changelog entry"
            name: "changelog"
            widget: "list"
            summary: "{{fields.date}}: {{fields.message}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Message", name: "message", widget: "string"}
      - label: "Best in Slot"
        name: "bis"
        file: "content/jobs/healers/scholar/best-in-slot.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "bis"}
          - {label: "Patch", name: "patch", widget: "string"}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Author(s)"
            name: "authors"
            widget: "relation"
            multiple: true
            collection: "author-profile"
            search_fields: ["username", "name"]
            value_field: "username"
            display_fields: ["username", "name"]
          - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
          - label: "Changelog entry"
            name: "changelog"
            widget: "list"
            summary: "{{fields.date}}: {{fields.message}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Message", name: "message", widget: "string"}
          - label: "Sets"
            name: "bis"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Type", name: "type", widget: "select", options: ["etro"], default: "etro"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown", required: false, default: ""}
      - label: "Stat Priority"
        name: "stat-priority"
        file: "content/jobs/healers/scholar/stat-priority.md"
        fields:
          - {label: "Patch", name: "patch", widget: "string"}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Author(s)"
            name: "authors"
            widget: "relation"
            multiple: true
            collection: "author-profile"
            search_fields: ["username", "name"]
            value_field: "username"
            display_fields: ["username", "name"]
          - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
          - label: "Changelog entry"
            name: "changelog"
            widget: "list"
            summary: "{{fields.date}}: {{fields.message}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Message", name: "message", widget: "string"}
          - {label: "Priority", name: "priority", widget: "string"}
      - label: "Job Changes"
        name: "job-changes"
        file: "content/jobs/healers/scholar/job-changes.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "changes"}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Change"
            name: "changes"
            widget: "list"
            summary: "{{fields.patch}}"
            fields:
              - {label: "Patch", name: "patch", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
      - label: "Fight tips"
        name: "fight-tips"
        file: "content/jobs/healers/scholar/fight-tips.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          - { label: "Card Header Image", name: "cardHeaderImage", widget: "image", choose_url: false, required: false }
          - label: "Author(s)"
            name: "authors"
            widget: "relation"
            multiple: true
            collection: "author-profile"
            search_fields: ["username", "name"]
            value_field: "username"
            display_fields: ["username", "name"]
          - {label: "Patch", name: "patch", widget: "string"}
          - {label: "Last Updated", name: "lastmod", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
          - label: "Changelog entry"
            name: "changelog"
            widget: "list"
            summary: "{{fields.date}}: {{fields.message}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
              - {label: "Message", name: "message", widget: "string"}
      
