baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "The Balance"
theme = "glam"

[menu]
  [[menu.main]]
    identifier = 'combat-jobs'
    name = 'Combat Jobs'
    url = '/jobs/'
    weight = 10
  [[menu.main]]
    identifier = 'encounters'
    name = 'Encounters'
    url = '/encounters/'
    weight = 20
  [[menu.header]]
    identifier = 'discord'
    name = 'Discord'
    url = 'https://discord.gg/thebalanceffxiv'
    weight = 60
  [[menu.footer]]
    identifier = 'info'
    name = 'Info'
    url = '/pages/'
    weight = 10

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1

[params]
  maxTierGearsets = 8 
  maxUltimateGearsets = 4
  maxGearsets = 12
  discord = 'discord.gg/thebalanceffxiv'
  copyrightMessage = 'Â© SQUARE ENIX CO., LTD. All Rights Reserved | FINAL FANTASY is a registered trademark of Square Enix Holdings Co., Ltd.'
