baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Balance Glam"
theme = "glam"

[menu]
  [[menu.main]]
    identifier = 'jobs'
    name = 'Combat Jobs'
    url = '/jobs/'
    weight = 10
  [[menu.main]]
    identifier = 'other-jobs'
    name = 'Other Jobs'
    url = '/jobs/'
    weight = 20
  [[menu.main]]
    identifier = 'encounters'
    name = 'Fight Encounters'
    url = '/encounters/'
    weight = 30
  [[menu.main]]
    identifier = 'tools'
    name = 'Tools'
    url = '/tools/'
    weight = 40
  [[menu.main]]
    identifier = 'other-guides'
    name = 'Other Guides'
    url = '/guides/'
    weight = 50
  [[menu.header]]
    identifier = 'news'
    name = 'Newsfeed'
    url = '/news/'
    weight = 60
  [[menu.footer]]
    identifier = 'info'
    name = 'Info'
    weight = 60

[params]
  maxLevel = 90
  maxTierGearsets = 8 
  maxUltimateGearsets = 4
  copyrightMessage = 'Â© SQUARE ENIX CO., LTD. All Rights Reserved | FINAL FANTASY is a registered trademark of Square Enix Holdings Co., Ltd.'
