baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Balance Glam"
theme = "glam_dev"

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'home'
    url = '/'
    weight = -1
  [[menu.main]]
    identifier = 'about'
    name = 'about'
    url = '/about/'
    weight = 100
